/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  DashboardDto
} from '../../model'



export type getAnnualSummaryResponse = {
  data: DashboardDto[];
  status: number;
  headers: Headers;
}

export const getGetAnnualSummaryUrl = () => {


  return `/api/dashboard/annual-summary`
}

export const getAnnualSummary = async ( options?: RequestInit): Promise<getAnnualSummaryResponse> => {
  
  const res = await fetch(getGetAnnualSummaryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}



export const getGetAnnualSummaryQueryKey = () => {
    return [`/api/dashboard/annual-summary`] as const;
    }

    
export const getGetAnnualSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getAnnualSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnnualSummary>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnnualSummaryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnnualSummary>>> = ({ signal }) => getAnnualSummary({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnnualSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAnnualSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getAnnualSummary>>>
export type GetAnnualSummaryQueryError = unknown


export function useGetAnnualSummary<TData = Awaited<ReturnType<typeof getAnnualSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnnualSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnnualSummary>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAnnualSummary<TData = Awaited<ReturnType<typeof getAnnualSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnnualSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnnualSummary>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAnnualSummary<TData = Awaited<ReturnType<typeof getAnnualSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnnualSummary>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAnnualSummary<TData = Awaited<ReturnType<typeof getAnnualSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnnualSummary>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAnnualSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



