/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */
import type { BookShopDto } from './bookShopDto';

export type BookResponseDtoShop = null | BookShopDto;
