/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */
import type { BookChangeAppliedAtDtoAppliedAt } from './bookChangeAppliedAtDtoAppliedAt';

export interface BookChangeAppliedAtDto {
  applied_at?: BookChangeAppliedAtDtoAppliedAt;
}
