/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardDto {
  average: number;
  balance: number;
  count: number;
  limit: number;
  total_amount: number;
  year: number;
}
