/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  ShopCreateDto,
  ShopResponseDto,
  ShopUpdateDto
} from '../../model'
import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


export type getAllShopsResponse = {
  data: ShopResponseDto[];
  status: number;
  headers: Headers;
}

export const getGetAllShopsUrl = () => {


  return `/shops`
}

export const getAllShops = async ( options?: RequestInit): Promise<getAllShopsResponse> => {
  
  return customFetch<Promise<getAllShopsResponse>>(getGetAllShopsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetAllShopsQueryKey = () => {
    return [`/shops`] as const;
    }

    
export const getGetAllShopsQueryOptions = <TData = Awaited<ReturnType<typeof getAllShops>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShops>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllShopsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllShops>>> = ({ signal }) => getAllShops({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllShops>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllShopsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllShops>>>
export type GetAllShopsQueryError = void


export function useGetAllShops<TData = Awaited<ReturnType<typeof getAllShops>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShops>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllShops>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllShops<TData = Awaited<ReturnType<typeof getAllShops>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShops>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllShops>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllShops<TData = Awaited<ReturnType<typeof getAllShops>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShops>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllShops<TData = Awaited<ReturnType<typeof getAllShops>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShops>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllShopsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type createShopResponse = {
  data: ShopResponseDto;
  status: number;
  headers: Headers;
}

export const getCreateShopUrl = () => {


  return `/shops`
}

export const createShop = async (shopCreateDto: ShopCreateDto, options?: RequestInit): Promise<createShopResponse> => {
  
  return customFetch<Promise<createShopResponse>>(getCreateShopUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      shopCreateDto,)
  }
);}




export const getCreateShopMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShop>>, TError,{data: ShopCreateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createShop>>, TError,{data: ShopCreateDto}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShop>>, {data: ShopCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  createShop(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateShopMutationResult = NonNullable<Awaited<ReturnType<typeof createShop>>>
    export type CreateShopMutationBody = ShopCreateDto
    export type CreateShopMutationError = void

    export const useCreateShop = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShop>>, TError,{data: ShopCreateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof createShop>>,
        TError,
        {data: ShopCreateDto},
        TContext
      > => {

      const mutationOptions = getCreateShopMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type getShopResponse = {
  data: ShopResponseDto;
  status: number;
  headers: Headers;
}

export const getGetShopUrl = (pubId: string,) => {


  return `/shops/${pubId}`
}

export const getShop = async (pubId: string, options?: RequestInit): Promise<getShopResponse> => {
  
  return customFetch<Promise<getShopResponse>>(getGetShopUrl(pubId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetShopQueryKey = (pubId: string,) => {
    return [`/shops/${pubId}`] as const;
    }

    
export const getGetShopQueryOptions = <TData = Awaited<ReturnType<typeof getShop>>, TError = void>(pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShop>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShopQueryKey(pubId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShop>>> = ({ signal }) => getShop(pubId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pubId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShop>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetShopQueryResult = NonNullable<Awaited<ReturnType<typeof getShop>>>
export type GetShopQueryError = void


export function useGetShop<TData = Awaited<ReturnType<typeof getShop>>, TError = void>(
 pubId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShop>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShop>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetShop<TData = Awaited<ReturnType<typeof getShop>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShop>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShop>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetShop<TData = Awaited<ReturnType<typeof getShop>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShop>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetShop<TData = Awaited<ReturnType<typeof getShop>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShop>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetShopQueryOptions(pubId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type updateShopResponse = {
  data: ShopResponseDto;
  status: number;
  headers: Headers;
}

export const getUpdateShopUrl = (pubId: string,) => {


  return `/shops/${pubId}`
}

export const updateShop = async (pubId: string,
    shopUpdateDto: ShopUpdateDto, options?: RequestInit): Promise<updateShopResponse> => {
  
  return customFetch<Promise<updateShopResponse>>(getUpdateShopUrl(pubId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      shopUpdateDto,)
  }
);}




export const getUpdateShopMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShop>>, TError,{pubId: string;data: ShopUpdateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateShop>>, TError,{pubId: string;data: ShopUpdateDto}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateShop>>, {pubId: string;data: ShopUpdateDto}> = (props) => {
          const {pubId,data} = props ?? {};

          return  updateShop(pubId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateShopMutationResult = NonNullable<Awaited<ReturnType<typeof updateShop>>>
    export type UpdateShopMutationBody = ShopUpdateDto
    export type UpdateShopMutationError = void

    export const useUpdateShop = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShop>>, TError,{pubId: string;data: ShopUpdateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateShop>>,
        TError,
        {pubId: string;data: ShopUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdateShopMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type deleteShopResponse = {
  data: void;
  status: number;
  headers: Headers;
}

export const getDeleteShopUrl = (pubId: string,) => {


  return `/shops/${pubId}`
}

export const deleteShop = async (pubId: string, options?: RequestInit): Promise<deleteShopResponse> => {
  
  return customFetch<Promise<deleteShopResponse>>(getDeleteShopUrl(pubId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteShopMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShop>>, TError,{pubId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteShop>>, TError,{pubId: string}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShop>>, {pubId: string}> = (props) => {
          const {pubId} = props ?? {};

          return  deleteShop(pubId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteShopMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShop>>>
    
    export type DeleteShopMutationError = void

    export const useDeleteShop = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShop>>, TError,{pubId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteShop>>,
        TError,
        {pubId: string},
        TContext
      > => {

      const mutationOptions = getDeleteShopMutationOptions(options);

      return useMutation(mutationOptions);
    }
    