/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  BookChangeAppliedAtDto,
  BookCreateDto,
  BookResponseDto,
  BookUpdateDto
} from '../../model'
import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


export type getAllBooksResponse = {
  data: BookResponseDto[];
  status: number;
  headers: Headers;
}

export const getGetAllBooksUrl = () => {


  return `/books`
}

export const getAllBooks = async ( options?: RequestInit): Promise<getAllBooksResponse> => {
  
  return customFetch<Promise<getAllBooksResponse>>(getGetAllBooksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetAllBooksQueryKey = () => {
    return [`/books`] as const;
    }

    
export const getGetAllBooksQueryOptions = <TData = Awaited<ReturnType<typeof getAllBooks>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBooks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBooksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBooks>>> = ({ signal }) => getAllBooks({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBooks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllBooksQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBooks>>>
export type GetAllBooksQueryError = unknown


export function useGetAllBooks<TData = Awaited<ReturnType<typeof getAllBooks>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBooks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBooks>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllBooks<TData = Awaited<ReturnType<typeof getAllBooks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBooks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBooks>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllBooks<TData = Awaited<ReturnType<typeof getAllBooks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBooks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllBooks<TData = Awaited<ReturnType<typeof getAllBooks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBooks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllBooksQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type createBookResponse = {
  data: BookResponseDto;
  status: number;
  headers: Headers;
}

export const getCreateBookUrl = () => {


  return `/books`
}

export const createBook = async (bookCreateDto: BookCreateDto, options?: RequestInit): Promise<createBookResponse> => {
  
  return customFetch<Promise<createBookResponse>>(getCreateBookUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookCreateDto,)
  }
);}




export const getCreateBookMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBook>>, TError,{data: BookCreateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createBook>>, TError,{data: BookCreateDto}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBook>>, {data: BookCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  createBook(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBookMutationResult = NonNullable<Awaited<ReturnType<typeof createBook>>>
    export type CreateBookMutationBody = BookCreateDto
    export type CreateBookMutationError = unknown

    export const useCreateBook = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBook>>, TError,{data: BookCreateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof createBook>>,
        TError,
        {data: BookCreateDto},
        TContext
      > => {

      const mutationOptions = getCreateBookMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type getYearAppliedBooksResponse = {
  data: BookResponseDto[];
  status: number;
  headers: Headers;
}

export const getGetYearAppliedBooksUrl = (year: number,) => {


  return `/books/applied/${year}`
}

export const getYearAppliedBooks = async (year: number, options?: RequestInit): Promise<getYearAppliedBooksResponse> => {
  
  return customFetch<Promise<getYearAppliedBooksResponse>>(getGetYearAppliedBooksUrl(year),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetYearAppliedBooksQueryKey = (year: number,) => {
    return [`/books/applied/${year}`] as const;
    }

    
export const getGetYearAppliedBooksQueryOptions = <TData = Awaited<ReturnType<typeof getYearAppliedBooks>>, TError = unknown>(year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearAppliedBooks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetYearAppliedBooksQueryKey(year);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getYearAppliedBooks>>> = ({ signal }) => getYearAppliedBooks(year, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(year), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getYearAppliedBooks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetYearAppliedBooksQueryResult = NonNullable<Awaited<ReturnType<typeof getYearAppliedBooks>>>
export type GetYearAppliedBooksQueryError = unknown


export function useGetYearAppliedBooks<TData = Awaited<ReturnType<typeof getYearAppliedBooks>>, TError = unknown>(
 year: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearAppliedBooks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getYearAppliedBooks>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetYearAppliedBooks<TData = Awaited<ReturnType<typeof getYearAppliedBooks>>, TError = unknown>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearAppliedBooks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getYearAppliedBooks>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetYearAppliedBooks<TData = Awaited<ReturnType<typeof getYearAppliedBooks>>, TError = unknown>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearAppliedBooks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetYearAppliedBooks<TData = Awaited<ReturnType<typeof getYearAppliedBooks>>, TError = unknown>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearAppliedBooks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetYearAppliedBooksQueryOptions(year,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type getBookResponse = {
  data: BookResponseDto;
  status: number;
  headers: Headers;
}

export const getGetBookUrl = (pubId: string,) => {


  return `/books/${pubId}`
}

export const getBook = async (pubId: string, options?: RequestInit): Promise<getBookResponse> => {
  
  return customFetch<Promise<getBookResponse>>(getGetBookUrl(pubId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetBookQueryKey = (pubId: string,) => {
    return [`/books/${pubId}`] as const;
    }

    
export const getGetBookQueryOptions = <TData = Awaited<ReturnType<typeof getBook>>, TError = void>(pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookQueryKey(pubId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBook>>> = ({ signal }) => getBook(pubId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pubId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetBookQueryResult = NonNullable<Awaited<ReturnType<typeof getBook>>>
export type GetBookQueryError = void


export function useGetBook<TData = Awaited<ReturnType<typeof getBook>>, TError = void>(
 pubId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBook>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetBook<TData = Awaited<ReturnType<typeof getBook>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBook>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetBook<TData = Awaited<ReturnType<typeof getBook>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetBook<TData = Awaited<ReturnType<typeof getBook>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBook>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetBookQueryOptions(pubId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type updateBookResponse = {
  data: BookResponseDto;
  status: number;
  headers: Headers;
}

export const getUpdateBookUrl = (pubId: string,) => {


  return `/books/${pubId}`
}

export const updateBook = async (pubId: string,
    bookUpdateDto: BookUpdateDto, options?: RequestInit): Promise<updateBookResponse> => {
  
  return customFetch<Promise<updateBookResponse>>(getUpdateBookUrl(pubId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookUpdateDto,)
  }
);}




export const getUpdateBookMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBook>>, TError,{pubId: string;data: BookUpdateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBook>>, TError,{pubId: string;data: BookUpdateDto}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBook>>, {pubId: string;data: BookUpdateDto}> = (props) => {
          const {pubId,data} = props ?? {};

          return  updateBook(pubId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBookMutationResult = NonNullable<Awaited<ReturnType<typeof updateBook>>>
    export type UpdateBookMutationBody = BookUpdateDto
    export type UpdateBookMutationError = void

    export const useUpdateBook = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBook>>, TError,{pubId: string;data: BookUpdateDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateBook>>,
        TError,
        {pubId: string;data: BookUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdateBookMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type deleteBookResponse = {
  data: void;
  status: number;
  headers: Headers;
}

export const getDeleteBookUrl = (pubId: string,) => {


  return `/books/${pubId}`
}

export const deleteBook = async (pubId: string, options?: RequestInit): Promise<deleteBookResponse> => {
  
  return customFetch<Promise<deleteBookResponse>>(getDeleteBookUrl(pubId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteBookMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBook>>, TError,{pubId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBook>>, TError,{pubId: string}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBook>>, {pubId: string}> = (props) => {
          const {pubId} = props ?? {};

          return  deleteBook(pubId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBookMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBook>>>
    
    export type DeleteBookMutationError = void

    export const useDeleteBook = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBook>>, TError,{pubId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteBook>>,
        TError,
        {pubId: string},
        TContext
      > => {

      const mutationOptions = getDeleteBookMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type changeBookAppliedAtResponse = {
  data: BookResponseDto;
  status: number;
  headers: Headers;
}

export const getChangeBookAppliedAtUrl = (pubId: string,) => {


  return `/books/${pubId}/applied_at`
}

export const changeBookAppliedAt = async (pubId: string,
    bookChangeAppliedAtDto: BookChangeAppliedAtDto, options?: RequestInit): Promise<changeBookAppliedAtResponse> => {
  
  return customFetch<Promise<changeBookAppliedAtResponse>>(getChangeBookAppliedAtUrl(pubId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookChangeAppliedAtDto,)
  }
);}




export const getChangeBookAppliedAtMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeBookAppliedAt>>, TError,{pubId: string;data: BookChangeAppliedAtDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeBookAppliedAt>>, TError,{pubId: string;data: BookChangeAppliedAtDto}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeBookAppliedAt>>, {pubId: string;data: BookChangeAppliedAtDto}> = (props) => {
          const {pubId,data} = props ?? {};

          return  changeBookAppliedAt(pubId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeBookAppliedAtMutationResult = NonNullable<Awaited<ReturnType<typeof changeBookAppliedAt>>>
    export type ChangeBookAppliedAtMutationBody = BookChangeAppliedAtDto
    export type ChangeBookAppliedAtMutationError = void

    export const useChangeBookAppliedAt = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeBookAppliedAt>>, TError,{pubId: string;data: BookChangeAppliedAtDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationResult<
        Awaited<ReturnType<typeof changeBookAppliedAt>>,
        TError,
        {pubId: string;data: BookChangeAppliedAtDto},
        TContext
      > => {

      const mutationOptions = getChangeBookAppliedAtMutationOptions(options);

      return useMutation(mutationOptions);
    }
    