/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Rust Web App
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  PublisherCreateDto,
  PublisherResponseDto,
  PublisherUpdateDto
} from '../../model'



export type getAllPublishersResponse = {
  data: PublisherResponseDto[];
  status: number;
  headers: Headers;
}

export const getGetAllPublishersUrl = () => {


  return `/api/publishers`
}

export const getAllPublishers = async ( options?: RequestInit): Promise<getAllPublishersResponse> => {
  
  const res = await fetch(getGetAllPublishersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}



export const getGetAllPublishersQueryKey = () => {
    return [`/api/publishers`] as const;
    }

    
export const getGetAllPublishersQueryOptions = <TData = Awaited<ReturnType<typeof getAllPublishers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPublishers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPublishersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPublishers>>> = ({ signal }) => getAllPublishers({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPublishers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllPublishersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPublishers>>>
export type GetAllPublishersQueryError = unknown


export function useGetAllPublishers<TData = Awaited<ReturnType<typeof getAllPublishers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPublishers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPublishers>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllPublishers<TData = Awaited<ReturnType<typeof getAllPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPublishers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPublishers>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllPublishers<TData = Awaited<ReturnType<typeof getAllPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPublishers>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllPublishers<TData = Awaited<ReturnType<typeof getAllPublishers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPublishers>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllPublishersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type createPublisherResponse = {
  data: PublisherResponseDto;
  status: number;
  headers: Headers;
}

export const getCreatePublisherUrl = () => {


  return `/api/publishers`
}

export const createPublisher = async (publisherCreateDto: PublisherCreateDto, options?: RequestInit): Promise<createPublisherResponse> => {
  
  const res = await fetch(getCreatePublisherUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publisherCreateDto,)
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}




export const getCreatePublisherMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPublisher>>, TError,{data: PublisherCreateDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createPublisher>>, TError,{data: PublisherCreateDto}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPublisher>>, {data: PublisherCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  createPublisher(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePublisherMutationResult = NonNullable<Awaited<ReturnType<typeof createPublisher>>>
    export type CreatePublisherMutationBody = PublisherCreateDto
    export type CreatePublisherMutationError = unknown

    export const useCreatePublisher = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPublisher>>, TError,{data: PublisherCreateDto}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof createPublisher>>,
        TError,
        {data: PublisherCreateDto},
        TContext
      > => {

      const mutationOptions = getCreatePublisherMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type getPublisherResponse = {
  data: PublisherResponseDto;
  status: number;
  headers: Headers;
}

export const getGetPublisherUrl = (pubId: string,) => {


  return `/api/publishers/${pubId}`
}

export const getPublisher = async (pubId: string, options?: RequestInit): Promise<getPublisherResponse> => {
  
  const res = await fetch(getGetPublisherUrl(pubId),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}



export const getGetPublisherQueryKey = (pubId: string,) => {
    return [`/api/publishers/${pubId}`] as const;
    }

    
export const getGetPublisherQueryOptions = <TData = Awaited<ReturnType<typeof getPublisher>>, TError = void>(pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublisher>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublisherQueryKey(pubId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublisher>>> = ({ signal }) => getPublisher(pubId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pubId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublisher>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPublisherQueryResult = NonNullable<Awaited<ReturnType<typeof getPublisher>>>
export type GetPublisherQueryError = void


export function useGetPublisher<TData = Awaited<ReturnType<typeof getPublisher>>, TError = void>(
 pubId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublisher>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublisher>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublisher<TData = Awaited<ReturnType<typeof getPublisher>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublisher>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublisher>>,
          TError,
          TData
        > , 'initialData'
      >, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublisher<TData = Awaited<ReturnType<typeof getPublisher>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublisher>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPublisher<TData = Awaited<ReturnType<typeof getPublisher>>, TError = void>(
 pubId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublisher>>, TError, TData>>, fetch?: RequestInit}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPublisherQueryOptions(pubId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export type updatePublisherResponse = {
  data: PublisherResponseDto;
  status: number;
  headers: Headers;
}

export const getUpdatePublisherUrl = (pubId: string,) => {


  return `/api/publishers/${pubId}`
}

export const updatePublisher = async (pubId: string,
    publisherUpdateDto: PublisherUpdateDto, options?: RequestInit): Promise<updatePublisherResponse> => {
  
  const res = await fetch(getUpdatePublisherUrl(pubId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publisherUpdateDto,)
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}




export const getUpdatePublisherMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePublisher>>, TError,{pubId: string;data: PublisherUpdateDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updatePublisher>>, TError,{pubId: string;data: PublisherUpdateDto}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePublisher>>, {pubId: string;data: PublisherUpdateDto}> = (props) => {
          const {pubId,data} = props ?? {};

          return  updatePublisher(pubId,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePublisherMutationResult = NonNullable<Awaited<ReturnType<typeof updatePublisher>>>
    export type UpdatePublisherMutationBody = PublisherUpdateDto
    export type UpdatePublisherMutationError = void

    export const useUpdatePublisher = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePublisher>>, TError,{pubId: string;data: PublisherUpdateDto}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof updatePublisher>>,
        TError,
        {pubId: string;data: PublisherUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdatePublisherMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export type deletePublisherResponse = {
  data: void;
  status: number;
  headers: Headers;
}

export const getDeletePublisherUrl = (pubId: string,) => {


  return `/api/publishers/${pubId}`
}

export const deletePublisher = async (pubId: string, options?: RequestInit): Promise<deletePublisherResponse> => {
  
  const res = await fetch(getDeletePublisherUrl(pubId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}




export const getDeletePublisherMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePublisher>>, TError,{pubId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deletePublisher>>, TError,{pubId: string}, TContext> => {
const {mutation: mutationOptions, fetch: fetchOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePublisher>>, {pubId: string}> = (props) => {
          const {pubId} = props ?? {};

          return  deletePublisher(pubId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePublisherMutationResult = NonNullable<Awaited<ReturnType<typeof deletePublisher>>>
    
    export type DeletePublisherMutationError = void

    export const useDeletePublisher = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePublisher>>, TError,{pubId: string}, TContext>, fetch?: RequestInit}
): UseMutationResult<
        Awaited<ReturnType<typeof deletePublisher>>,
        TError,
        {pubId: string},
        TContext
      > => {

      const mutationOptions = getDeletePublisherMutationOptions(options);

      return useMutation(mutationOptions);
    }
    